spring:
 application:
  name: libraryapi 
 datasource:
  url: jdbc:postgresql://localhost:5432/library
  username: postgres
  password: postgres
  driver-class-name: org.postgresql.Driver
  #ESSA CONFIGURA JPA -- CRIA O BANCO DE ACORDO COM AS ENTIDADES ANOTADAS COM ENTITY .
  jpa:
   hibernate:
   ddl-auto: update,none,create-drop
   
  
  